name: davinci
description: A package to convert any widget to an image which can be saved locally or can be shared to other apps and chats.
version: 2.5.1
homepage: https://gokula.dev
repository: https://github.com/Imgkl/Davinci
issue_tracker: https://github.com/Imgkl/Davinci/issues
topics: [screenshots, image-capture, dynamic-image-generation]

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  gal: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

platforms:
  android:
  ios:
  web:
